### ISSUE TITLE
DK 11208 labels (38mm x 90mm).

### ISSUE THREAD

**Issue by imbeingfollowed** [sudomesh/ql570#3]
Hi,

Could you please help me add support for DK 11208 labels (38mm x 90mm).

I expect that it follows closely to the PAPER_QL700 format, but I'm not quite sure what all the hex values correspond to in order for me to add this compatibility.

Best wishes,

James

**Comment by Juul** [comment]
Hm.

Try to change line 89 to the following and let me know if it works:

```
fprintf(fp, "%c%c%c%c%c%c%c%c%c%c%c%c%c", ESC, 'i', 'z', 0x0e, 0x0b,
0x26, 0x5a, 0xdf, 0x03, 0, 0, 0, 0);
```

If it doesn't work then there's nothing else I can do without having a
roll of this paper. You could send me a roll but I'm on vacation
starting soon and until January 15th so I wouldn't be able to
implement this until around the end of January.

You can try to change around the 0x0e and 0x0b values but I have no
good suggestions about what they should be. The way to figure it out
would be too use the proprietary linux drivers from Brother and listen
to what's being sent over USB when you print.

**Comment by soundstorm** [comment]
I've just written a little python script to dump socket data. Configured the socket as LPD on my Mac with the original driver. Makes it easier than sniffing USB ;)
